### ISSUE TITLE
Bug MongoDB

### ISSUE THREAD

**Issue by CleyssonDias** [JDaniloC/Individual-Bet365Bot#17]
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.5) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from src.database import MongoDB
  File "/home/c/Desktop/Individual-Bet365Bot-master/src/database.py", line 100, in <module>
    MongoDB.cadastrar("alineli***1927", "lucas1**27")
  File "/home/c/Desktop/Individual-Bet365Bot-master/src/database.py", line 47, in cadastrar
    self.Users_collection.insert_one(user)
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/collection.py", line 698, in insert_one
    self._insert(document,
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/collection.py", line 613, in _insert
    return self._insert_one(
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/collection.py", line 602, in _insert_one
    self.__database.client._retryable_write(
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1498, in _retryable_write
    return self._retry_with_session(retryable, func, s, None)
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1384, in _retry_with_session
    return self._retry_internal(retryable, func, session, bulk)
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/mongo_client.py", line 1416, in _retry_internal
    return func(session, sock_info, retryable)
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/collection.py", line 590, in _insert_command
    result = sock_info.command(
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/pool.py", line 683, in command
    return command(self, dbname, spec, slave_ok,
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/network.py", line 159, in command
    helpers._check_command_response(
  File "/home/c/.local/lib/python3.8/site-packages/pymongo/helpers.py", line 164, in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)
pymongo.errors.OperationFailure: user is not allowed to do action [insert] on [betbot.users], full error: {'ok': 0, 'errmsg': 'user is not allowed to do action [insert] on [betbot.users]', 'code': 8000, 'codeName': 'AtlasError'}

**Comment by CleyssonDias** [comment]
ja resolvi

**Comment by JDaniloC** [comment]
Provavelmente era apenas uma questão de permissão de usuário ;D
Obrigado por colaborar, e se você deu alguma star ;D
